### ISSUE TITLE
Directory does not exist ${ORIG_FILENAME}.dump/2 BIOS region/2 8C8CE578-8A3D-4F1C-9935-896185C32DD3

### ISSUE THREAD

**Issue by jsparber** [purism/purism-librem-coreboot-updater#1]
The directory "${ORIG_FILENAME}.dump/2 BIOS region/2 8C8CE578-8A3D-4F1C-9935-896185C32DD3" but "${ORIG_FILENAME}.dump/2 BIOS region/3 8C8CE578-8A3D-4F1C-9935-896185C32DD3" exists.
When I change 379 from
` cp "${ORIG_FILENAME}.dump/2 BIOS region/2 8C8CE578-8A3D-4F1C-9935-896185C32DD3/2 9E21FD93-9C72-4C15-8C4B-E77F1DB2D792/0 EE4E5898-3914-4259-9D6E-DC7BD79403CF/1 Volume image section/0 8C8CE578-8A3D-4F1C-9935-896185C32DD3/237 A0327FE0-1FDA-4E5B-905D-B510C45A61D0/0 EE4E5898-3914-4259-9D6E-DC7BD79403CF/1 C5A4306E-E247-4ECD-A9D8-5B1985D3DCDA/body.bin" ${VGABIOS_FILENAME}`
to
` cp "${ORIG_FILENAME}.dump/2 BIOS region/3 8C8CE578-8A3D-4F1C-9935-896185C32DD3/2 9E21FD93-9C72-4C15-8C4B-E77F1DB2D792/0 EE4E5898-3914-4259-9D6E-DC7BD79403CF/1 Volume image section/0 8C8CE578-8A3D-4F1C-9935-896185C32DD3/237 A0327FE0-1FDA-4E5B-905D-B510C45A61D0/0 EE4E5898-3914-4259-9D6E-DC7BD79403CF/1 C5A4306E-E247-4ECD-A9D8-5B1985D3DCDA/body.bin" ${VGABIOS_FILENAME}`
the script creates the coreboot image. It should be the right file because it passes the sha checksum.

I'm using Parabola x86_64.

The content of the directory

- factory_bios_backup.rom.dump:
`
'0 Descriptor region'  '1 ME region'  '2 BIOS region'   body.bin   info.txt
`

- factory_bios_backup.rom.dump/2 BIOS region:
`'0 8C8CE578-8A3D-4F1C-9935-896185C32DD3'  '3 8C8CE578-8A3D-4F1C-9935-896185C32DD3'   body.bin
'1 8C8CE578-8A3D-4F1C-9935-896185C32DD3'  '4 8C8CE578-8A3D-4F1C-9935-896185C32DD3'   info.txt
'2 Padding'				  '5 8C8CE578-8A3D-4F1C-9935-896185C32DD3'`

-  factory_bios_backup.rom.dump/2 BIOS region/2 Padding:
body.bin  info.txt
body.bin contains a long sequence of 111111...

Should I try to flash it? Or would you say its to risky.

**Comment by ximion** [comment]
@KaKaRoTo

**Comment by ximion** [comment]
@KaKaRoTo, can you take a look at this?

**Comment by jsparber** [comment]
I think I got do exiting and could not wait. I tryed to flash it... Should not have done it. The librem loads seabios, but then it blocks at "Booting from Hard Disk".  A pen drive gets recronized, but it also blocks at the same msg. Memtest works without problems.

**Comment by toddatpurism** [comment]
So you got coreboot + seabios, that is better than a brick. I am adding
Youness directly to this email thread.

Todd.

**Comment by jsparber** [comment]
Maybe its a systemd-boot (gummiboot) problem. Does seabios support systemd-boot? I searched a little bit and could not find much information on that. In the archlinux wiki they say you should use grub on chrome os devices with a custom firmware. (https://wiki.archlinux.org/index.php/Chrome_OS_devices)
Tomorrow I will try to boot from a diffrent usb dongle, with grub installed.

**Comment by jsparber** [comment]
I created a usb dongle with pureos 3 and it boots. Hurray!
It seam working fine, for now but the pci express ssd is not recognized.

**Comment by kakaroto** [comment]
Hey @jsparber, someone who loves to live a risky life! I'm really glad that you at least got coreboot+seabios to work, so it's not a brick (otherwise it's very annoying to try and flash it with hardware, see https://puri.sm/posts/preventing-interference-from-the-old-bios-while-flashing-coreboot/).

I suppose that it's fine if the path is not exactly the same, that '2' vs '3' is just the index in the UEFI tree. I'll change the script so it can find the file regardless of the index.

I'm assuming that you used the live USB to flash back your original bios ? If you followed the script's instructions, then you made external copies of the files, so you should have access to your original bios . If you haven't done it yet, then you should be able to flash it back with the command :
```sudo flashrom -p internal:laptop=force_I_want_a_brick -c MX25L6406E/MX25L6408E -w factory_bios_backup.rom```
For the ssd not being recognized, I'll answer on that issue directly. Thanks for being brave!

By the way, if you have any other comments, please share them. What did you think of the script, was it easy enough to use? Is there some text that wasn't immediatly clear and you think it needs to be fixed, did you notice any typos, stuff like that.
Thanks!

**Comment by jsparber** [comment]
The script is quite easy to use and I had no big issues.
You should add a description on how to flash back the factory bios.
And build the coreboot rom from source (somebody already created an issues for that).

**Comment by kakaroto** [comment]
Ok thanks for the feedback, and yes, it's a good idea for the instructions on how to flash back the factory bios.
I was hoping to eventually make it into an argument, such as "run the script with the .rom you want to flash and it will flash that directly" so users who want to build their own coreboot from source, can still just pass it to the script. Adding instructions to that feature (or to manual command in the meantime) is a good idea. I'll make an issue out of it.
The issue about building coreboot from source is about the packaging system doing it instead of using my hardcoded URL for the one I prebuilt myself, not about the script itself building it for users.
Instructions though will probably be posted as a blog post once it's all done.

In the meantime, it should be pretty straightforward, use this config file : https://review.coreboot.org/cgit/board-status.git/tree/purism/librem13/4.5-1503-gfe41ae9/2017-04-07T19_59_53Z/config.txt?
Put the files vgabios.bin, mrc.bin, refcode.elf, me.bin, descriptor.bin in 3rdparty/blobs/mainboard/purism/librem13/
and bootorder.txt and bootsplash.jpg in the coreboot root directory, then 'make' should do the work.
(You'd first need to do the make cross-gcc so it compiles the cross compilers, and do an initial 'make' so it checks out the 3rdparty submodules)
Note that this is off the top of my head, and I haven't tested this out on a freshly checked out repo (or a clean machine to check for dependencies to apt-get).

**Comment by kakaroto** [comment]
I've replaced the long path with a "$(find ${ORIG_FILENAME}.dump -name '* C5A4306E-E247-4ECD-A9D8-5B1985D3DCDA')/body.bin" which should fix your issue. 
Thanks for reporting it!
